/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as LessonZeroRouteImport } from './routes/lesson-zero'
import { Route as DiscoverRouteImport } from './routes/discover'
import { Route as CredentialsRouteImport } from './routes/credentials'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ConversationIndexRouteImport } from './routes/conversation.index'
import { Route as VerifyTokenIdRouteImport } from './routes/verify.$tokenId'
import { Route as ConversationSubjectRouteImport } from './routes/conversation.$subject'

const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const LessonZeroRoute = LessonZeroRouteImport.update({
  id: '/lesson-zero',
  path: '/lesson-zero',
  getParentRoute: () => rootRouteImport,
} as any)
const DiscoverRoute = DiscoverRouteImport.update({
  id: '/discover',
  path: '/discover',
  getParentRoute: () => rootRouteImport,
} as any)
const CredentialsRoute = CredentialsRouteImport.update({
  id: '/credentials',
  path: '/credentials',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ConversationIndexRoute = ConversationIndexRouteImport.update({
  id: '/conversation/',
  path: '/conversation/',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifyTokenIdRoute = VerifyTokenIdRouteImport.update({
  id: '/verify/$tokenId',
  path: '/verify/$tokenId',
  getParentRoute: () => rootRouteImport,
} as any)
const ConversationSubjectRoute = ConversationSubjectRouteImport.update({
  id: '/conversation/$subject',
  path: '/conversation/$subject',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/credentials': typeof CredentialsRoute
  '/discover': typeof DiscoverRoute
  '/lesson-zero': typeof LessonZeroRoute
  '/profile': typeof ProfileRoute
  '/conversation/$subject': typeof ConversationSubjectRoute
  '/verify/$tokenId': typeof VerifyTokenIdRoute
  '/conversation/': typeof ConversationIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/credentials': typeof CredentialsRoute
  '/discover': typeof DiscoverRoute
  '/lesson-zero': typeof LessonZeroRoute
  '/profile': typeof ProfileRoute
  '/conversation/$subject': typeof ConversationSubjectRoute
  '/verify/$tokenId': typeof VerifyTokenIdRoute
  '/conversation': typeof ConversationIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/credentials': typeof CredentialsRoute
  '/discover': typeof DiscoverRoute
  '/lesson-zero': typeof LessonZeroRoute
  '/profile': typeof ProfileRoute
  '/conversation/$subject': typeof ConversationSubjectRoute
  '/verify/$tokenId': typeof VerifyTokenIdRoute
  '/conversation/': typeof ConversationIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/credentials'
    | '/discover'
    | '/lesson-zero'
    | '/profile'
    | '/conversation/$subject'
    | '/verify/$tokenId'
    | '/conversation/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/credentials'
    | '/discover'
    | '/lesson-zero'
    | '/profile'
    | '/conversation/$subject'
    | '/verify/$tokenId'
    | '/conversation'
  id:
    | '__root__'
    | '/'
    | '/credentials'
    | '/discover'
    | '/lesson-zero'
    | '/profile'
    | '/conversation/$subject'
    | '/verify/$tokenId'
    | '/conversation/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CredentialsRoute: typeof CredentialsRoute
  DiscoverRoute: typeof DiscoverRoute
  LessonZeroRoute: typeof LessonZeroRoute
  ProfileRoute: typeof ProfileRoute
  ConversationSubjectRoute: typeof ConversationSubjectRoute
  VerifyTokenIdRoute: typeof VerifyTokenIdRoute
  ConversationIndexRoute: typeof ConversationIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lesson-zero': {
      id: '/lesson-zero'
      path: '/lesson-zero'
      fullPath: '/lesson-zero'
      preLoaderRoute: typeof LessonZeroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/discover': {
      id: '/discover'
      path: '/discover'
      fullPath: '/discover'
      preLoaderRoute: typeof DiscoverRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/credentials': {
      id: '/credentials'
      path: '/credentials'
      fullPath: '/credentials'
      preLoaderRoute: typeof CredentialsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conversation/': {
      id: '/conversation/'
      path: '/conversation'
      fullPath: '/conversation/'
      preLoaderRoute: typeof ConversationIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify/$tokenId': {
      id: '/verify/$tokenId'
      path: '/verify/$tokenId'
      fullPath: '/verify/$tokenId'
      preLoaderRoute: typeof VerifyTokenIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conversation/$subject': {
      id: '/conversation/$subject'
      path: '/conversation/$subject'
      fullPath: '/conversation/$subject'
      preLoaderRoute: typeof ConversationSubjectRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CredentialsRoute: CredentialsRoute,
  DiscoverRoute: DiscoverRoute,
  LessonZeroRoute: LessonZeroRoute,
  ProfileRoute: ProfileRoute,
  ConversationSubjectRoute: ConversationSubjectRoute,
  VerifyTokenIdRoute: VerifyTokenIdRoute,
  ConversationIndexRoute: ConversationIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
